/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    workouts: Workout;
    'workout-templates': WorkoutTemplate;
    goals: Goal;
    'goal-activity-records': GoalActivityRecord;
    exercises: Exercise;
    'body-state': BodyState;
    'body-fat': BodyFat;
    'body-measurements': BodyMeasurement;
    'body-photos': BodyPhoto;
    debts: Debt;
    'potential-debts': PotentialDebt;
    'planned-payments': PlannedPayment;
    'desired-expenses': DesiredExpense;
    incomes: Income;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    workouts: WorkoutsSelect<false> | WorkoutsSelect<true>;
    'workout-templates': WorkoutTemplatesSelect<false> | WorkoutTemplatesSelect<true>;
    goals: GoalsSelect<false> | GoalsSelect<true>;
    'goal-activity-records': GoalActivityRecordsSelect<false> | GoalActivityRecordsSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    'body-state': BodyStateSelect<false> | BodyStateSelect<true>;
    'body-fat': BodyFatSelect<false> | BodyFatSelect<true>;
    'body-measurements': BodyMeasurementsSelect<false> | BodyMeasurementsSelect<true>;
    'body-photos': BodyPhotosSelect<false> | BodyPhotosSelect<true>;
    debts: DebtsSelect<false> | DebtsSelect<true>;
    'potential-debts': PotentialDebtsSelect<false> | PotentialDebtsSelect<true>;
    'planned-payments': PlannedPaymentsSelect<false> | PlannedPaymentsSelect<true>;
    'desired-expenses': DesiredExpensesSelect<false> | DesiredExpensesSelect<true>;
    incomes: IncomesSelect<false> | IncomesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts".
 */
export interface Workout {
  id: string;
  name: string;
  date: string;
  template?: (string | null) | WorkoutTemplate;
  exercises?:
    | {
        name: string;
        exerciseType: 'strength' | 'cardio';
        sets?:
          | {
              reps?: string | null;
              weight?: string | null;
              duration?: string | null;
              distance?: string | null;
              notes?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  duration?: number | null;
  isSkip?: boolean | null;
  skipEndDate?: string | null;
  skipReason?:
    | ('injury' | 'illness' | 'gym-closed' | 'natural-disaster' | 'work' | 'travel' | 'family' | 'lazy' | 'other')
    | null;
  customReason?: string | null;
  skipColor?: ('blue' | 'red' | 'orange' | 'yellow') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-templates".
 */
export interface WorkoutTemplate {
  id: string;
  name: string;
  description?: string | null;
  exercises?:
    | {
        name: string;
        exerciseType: 'strength' | 'cardio';
        sets: number;
        reps?: string | null;
        weight?: string | null;
        duration?: string | null;
        distance?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goals".
 */
export interface Goal {
  id: string;
  /**
   * Например: Бросить курить, Научиться прыгать на скакалке
   */
  name: string;
  date: string;
  /**
   * Дата, когда цель была завершена (опционально)
   */
  endDate?: string | null;
  /**
   * Например: сигарет, секунд, раз и т.д.
   */
  unit?: string | null;
  /**
   * Дополнительные заметки о цели
   */
  notes?: string | null;
  /**
   * Изображение, которое будет использоваться как фон карточки цели в статистике
   */
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goal-activity-records".
 */
export interface GoalActivityRecord {
  id: string;
  /**
   * Глобальная цель, к которой относится эта запись активности
   */
  goal: string | Goal;
  /**
   * Дата, за которую записывается активность
   */
  date: string;
  /**
   * Значение активности за этот день (например, количество сигарет, секунды прыжков)
   */
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: string;
  name: string;
  exerciseType: 'strength' | 'cardio';
  muscleGroup?: ('chest' | 'back' | 'shoulders' | 'arms' | 'legs' | 'core' | 'cardio' | 'other') | null;
  description?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-state".
 */
export interface BodyState {
  id: string;
  /**
   * Ваш вес на дату записи
   */
  weight: number;
  /**
   * Дата, когда была сделана запись
   */
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-fat".
 */
export interface BodyFat {
  id: string;
  /**
   * Процент жира в организме на дату записи
   */
  value: number;
  /**
   * Дата, когда была сделана запись
   */
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-measurements".
 */
export interface BodyMeasurement {
  id: string;
  /**
   * Дата замера
   */
  date: string;
  /**
   * Вес на дату замера
   */
  weight?: number | null;
  /**
   * Процент жира на дату замера
   */
  bodyFat?: number | null;
  /**
   * Обхват шея, см
   */
  neck?: number | null;
  /**
   * Обхват плечи, см
   */
  shoulders?: number | null;
  /**
   * Обхват грудь, см
   */
  chest?: number | null;
  /**
   * Обхват талия, см
   */
  waist?: number | null;
  /**
   * Обхват бёдра, см
   */
  hips?: number | null;
  /**
   * Обхват бицепс, см
   */
  biceps?: number | null;
  /**
   * Обхват предплечье, см
   */
  forearm?: number | null;
  /**
   * Обхват бедро, см
   */
  thigh?: number | null;
  /**
   * Обхват голень, см
   */
  calf?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-photos".
 */
export interface BodyPhoto {
  id: string;
  /**
   * Дата съёмки
   */
  date: string;
  /**
   * Фото спереди
   */
  front?: (string | null) | Media;
  /**
   * Фото сзади
   */
  back?: (string | null) | Media;
  /**
   * Фото слева
   */
  left?: (string | null) | Media;
  /**
   * Фото справа
   */
  right?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debts".
 */
export interface Debt {
  id: string;
  /**
   * Сумма долга в евро
   */
  amount: number;
  /**
   * Например: Иван мне, Я Маше
   */
  who: string;
  /**
   * Уровень важности долга
   */
  priority: 'low' | 'normal' | 'high';
  /**
   * Когда планируется вернуть долг (опционально)
   */
  returnDate?: string | null;
  /**
   * Включить, если долг имеет ежемесячные платежи — попадает в обязательный месячный долг
   */
  isMonthlyPayment?: boolean | null;
  /**
   * Сумма ежемесячного платежа (только когда включён график платежей)
   */
  monthlyAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "potential-debts".
 */
export interface PotentialDebt {
  id: string;
  /**
   * Сумма потенциального долга в евро
   */
  amount: number;
  /**
   * Например: Иван мне, Я Маше
   */
  who: string;
  /**
   * Уровень важности
   */
  priority: 'low' | 'normal' | 'high';
  /**
   * Когда планируется вернуть (опционально)
   */
  returnDate?: string | null;
  /**
   * Включить, если есть ежемесячные платежи
   */
  isMonthlyPayment?: boolean | null;
  /**
   * Сумма ежемесячного платежа
   */
  monthlyAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planned-payments".
 */
export interface PlannedPayment {
  id: string;
  /**
   * Например: Spotify, Netflix, спортзал
   */
  name: string;
  /**
   * Ежемесячная сумма платежа
   */
  amount: number;
  /**
   * Уровень важности платежа
   */
  priority: 'low' | 'normal' | 'high';
  /**
   * Опционально: дата списания, ссылка на отмену и т.д.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desired-expenses".
 */
export interface DesiredExpense {
  id: string;
  /**
   * Например: Машина, новый iPhone, отпуск
   */
  name: string;
  /**
   * Сколько хотите потратить
   */
  amount: number;
  /**
   * Опционально: к какому времени хотите купить (например, к лету)
   */
  targetDate?: string | null;
  /**
   * Насколько важно для вас
   */
  priority: 'low' | 'normal' | 'high';
  /**
   * Опционально
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incomes".
 */
export interface Income {
  id: string;
  /**
   * Сумма дохода в месяц
   */
  amount: number;
  /**
   * Например: Зарплата, Фриланс, Аренда
   */
  source: string;
  /**
   * День месяца, когда приходит доход (опционально)
   */
  receiptDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'workouts';
        value: string | Workout;
      } | null)
    | ({
        relationTo: 'workout-templates';
        value: string | WorkoutTemplate;
      } | null)
    | ({
        relationTo: 'goals';
        value: string | Goal;
      } | null)
    | ({
        relationTo: 'goal-activity-records';
        value: string | GoalActivityRecord;
      } | null)
    | ({
        relationTo: 'exercises';
        value: string | Exercise;
      } | null)
    | ({
        relationTo: 'body-state';
        value: string | BodyState;
      } | null)
    | ({
        relationTo: 'body-fat';
        value: string | BodyFat;
      } | null)
    | ({
        relationTo: 'body-measurements';
        value: string | BodyMeasurement;
      } | null)
    | ({
        relationTo: 'body-photos';
        value: string | BodyPhoto;
      } | null)
    | ({
        relationTo: 'debts';
        value: string | Debt;
      } | null)
    | ({
        relationTo: 'potential-debts';
        value: string | PotentialDebt;
      } | null)
    | ({
        relationTo: 'planned-payments';
        value: string | PlannedPayment;
      } | null)
    | ({
        relationTo: 'desired-expenses';
        value: string | DesiredExpense;
      } | null)
    | ({
        relationTo: 'incomes';
        value: string | Income;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts_select".
 */
export interface WorkoutsSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  template?: T;
  exercises?:
    | T
    | {
        name?: T;
        exerciseType?: T;
        sets?:
          | T
          | {
              reps?: T;
              weight?: T;
              duration?: T;
              distance?: T;
              notes?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  duration?: T;
  isSkip?: T;
  skipEndDate?: T;
  skipReason?: T;
  customReason?: T;
  skipColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-templates_select".
 */
export interface WorkoutTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  exercises?:
    | T
    | {
        name?: T;
        exerciseType?: T;
        sets?: T;
        reps?: T;
        weight?: T;
        duration?: T;
        distance?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goals_select".
 */
export interface GoalsSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  endDate?: T;
  unit?: T;
  notes?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goal-activity-records_select".
 */
export interface GoalActivityRecordsSelect<T extends boolean = true> {
  goal?: T;
  date?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  name?: T;
  exerciseType?: T;
  muscleGroup?: T;
  description?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-state_select".
 */
export interface BodyStateSelect<T extends boolean = true> {
  weight?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-fat_select".
 */
export interface BodyFatSelect<T extends boolean = true> {
  value?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-measurements_select".
 */
export interface BodyMeasurementsSelect<T extends boolean = true> {
  date?: T;
  weight?: T;
  bodyFat?: T;
  neck?: T;
  shoulders?: T;
  chest?: T;
  waist?: T;
  hips?: T;
  biceps?: T;
  forearm?: T;
  thigh?: T;
  calf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-photos_select".
 */
export interface BodyPhotosSelect<T extends boolean = true> {
  date?: T;
  front?: T;
  back?: T;
  left?: T;
  right?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debts_select".
 */
export interface DebtsSelect<T extends boolean = true> {
  amount?: T;
  who?: T;
  priority?: T;
  returnDate?: T;
  isMonthlyPayment?: T;
  monthlyAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "potential-debts_select".
 */
export interface PotentialDebtsSelect<T extends boolean = true> {
  amount?: T;
  who?: T;
  priority?: T;
  returnDate?: T;
  isMonthlyPayment?: T;
  monthlyAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planned-payments_select".
 */
export interface PlannedPaymentsSelect<T extends boolean = true> {
  name?: T;
  amount?: T;
  priority?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desired-expenses_select".
 */
export interface DesiredExpensesSelect<T extends boolean = true> {
  name?: T;
  amount?: T;
  targetDate?: T;
  priority?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incomes_select".
 */
export interface IncomesSelect<T extends boolean = true> {
  amount?: T;
  source?: T;
  receiptDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}